using System;
using System.Diagnostics;

public abstract partial class PacketWarden<T> : IDisposable
    where T : IPacket, new()
{
    /// <summary>
    /// Standard server-side pipeline for incoming packets. <br/>
    /// RateLimit -> Auth Check -> Sanitize -> Validate -> ProcessApprovedPacket
    /// </summary>
    protected void WhenServerReceivesPacket(ref T packet, int peerId)
    {
#if UNITY_EDITOR || DEBUG
        if (ShouldLog)
            UnityEngine.Debug.Log(
                $"[PacketWarden] Receiving {typeof(T).Name} from Peer {peerId} at {UnityEngine.Time.time}"
            );
#endif

        if (!TryPassServerRateLimit(packet, peerId))
            return;

        if (IsUnauthorized(peerId))
        {
            SendRejection(ref packet, peerId, $"You are not authorized to send {typeof(T).Name}");
            return;
        }

        if (!SanitizeMetadata(ref packet, peerId, out string sanitizationRejectionReason))
        {
            SendRejection(ref packet, peerId, sanitizationRejectionReason);
            return;
        }

        if (!ValidatePacket(in packet, peerId, out string rejectionReason))
        {
            SendRejection(ref packet, peerId, rejectionReason);
            return;
        }

        ProcessApprovedPacket(ref packet, peerId);
    }

    /// <summary>
    /// Evaluates the peer against the token bucket rate limiter. <br/>
    /// Returns true if the packet is allowed through.
    /// </summary>
    protected bool TryPassServerRateLimit(T packet, int peerId)
    {
        var config = ServerRateLimit;
        if (!config.Enabled)
            return true;

        double nowSeconds = Stopwatch.GetTimestamp() / (double)Stopwatch.Frequency;

        _serverRateLimiter.Prune(nowSeconds, config.StateTtlSeconds);

        bool allowed = _serverRateLimiter.TryConsume(
            peerId,
            nowSeconds,
            config,
            out bool canSendReject
        );
        if (allowed)
            return true;

        OnRateLimited(packet, peerId, config);

        switch (config.Action)
        {
            case RateLimitAction.Drop:
                return false;
            case RateLimitAction.Reject:
                if (canSendReject)
                    SendRejection(
                        ref packet,
                        peerId,
                        $"You've been rate limited. ({typeof(T).Name})"
                    );
                return false;
            case RateLimitAction.Disconnect:
                Network.DisconnectPeer(peerId);
                return false;
            default:
                return false;
        }
    }

    /// <summary>
    /// Evaluates whether a peer ID is unauthorized to send this packet based on the <see cref="Authority"/> config.
    /// </summary>
    protected virtual bool IsUnauthorized(int id) => false;

    /// <summary>
    /// Protects against spoofing. <br/>
    /// Ensures that an <see cref="IAuthoredPacket"/>  was actually generated by the player representing that peer ID.
    /// </summary>
    protected virtual bool SanitizeMetadata(ref T packet, int peerId, out string rejectionReason)
    {
        rejectionReason = null;
        return true;
    }

    /// <summary>
    /// Allows inheritors to provide custom gameplay validation logic (e.g., checking if the player has enough money).
    /// </summary>
    /// <returns>True if valid, false to abort and send a rejection.</returns>
    protected virtual bool ValidatePacket(in T packet, int peerId, out string rejectionReason)
    {
        rejectionReason = string.Empty;
        return true;
    }

    /// <summary>
    /// Called after a packet passes all validation and rate limits on the server. <br/>
    /// Mutates the packet, broadcasts it to clients, and applies it locally. <br/>
    /// <b>OVERRIDE THIS METHOD ONLY TO DEFER PACKET APPLICATION OR MODIFY WHO GETS THE INFORMATION <br/>
    /// USE MUTATEAPPROVEDPACKET AND APPLY FOR ALL THE ACTUAL PACKET LOGIC</b>
    /// </summary>
    protected virtual void ProcessApprovedPacket(ref T packet, int peerId)
    {
        MutateApprovedPacket(ref packet, peerId);
        Network.SendData(ref packet, DeliveryType); // Broadcast
        Apply(ref packet, peerId);
    }

    /// <summary>
    /// Allows the server to alter packet data before broadcasting it (e.g., forcing a server-authoritative Timestamp).
    /// </summary>
    protected virtual void MutateApprovedPacket(ref T packet, int peerId) { }

    /// <summary>
    /// Sends a <see cref="RejectionPacket{T}"/> back to the offending peer.
    /// </summary>
    protected void SendRejection(ref T packet, int peerId, string rejectionReason = null)
    {
        var rejected = new RejectionPacket<T>
        {
            Payload = packet,
            rejectionReason = rejectionReason,
        };
        Network.SendDataToPeer(ref rejected, DeliveryType, peerId);
    }

    /// <summary>
    /// Invoked when a peer exceeds the ServerRateLimit threshold.
    /// </summary>
    protected virtual void OnRateLimited(T packet, int peerId, in RateLimitConfig config)
    {
        UnityEngine.Debug.Log($"Rate-limiting peer {peerId}, Packet {GetType().Name}");
    }
}
